/* Generated By:JavaCC: Do not edit this line. RelationalQueryLanguage.java */
package br.edu.ifsp.parser;

/*
 * Import session
 */
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import br.edu.ifsp.codeGeneration.CodeGenerator;
import br.edu.ifsp.semanticAnalysis.RelationCheck;
import br.edu.ifsp.symbolTable.Attribute;
import br.edu.ifsp.symbolTable.Reference;
import br.edu.ifsp.symbolTable.SymbolTable;
import br.edu.ifsp.symbolTable.exceptions.UnexistentForeignKeyException;
import br.edu.ifsp.syntacticTree.AdditionOperatorNode;
import br.edu.ifsp.syntacticTree.AdditionSentenceNode;
import br.edu.ifsp.syntacticTree.AttributeNode;
import br.edu.ifsp.syntacticTree.BinaryOperationsNode;
import br.edu.ifsp.syntacticTree.BinarySetNode;
import br.edu.ifsp.syntacticTree.ComparisonOperatorNode;
import br.edu.ifsp.syntacticTree.ComparisonSentenceNode;
import br.edu.ifsp.syntacticTree.ConditionalSentenceNode;
import br.edu.ifsp.syntacticTree.CrossJoinNode;
import br.edu.ifsp.syntacticTree.DifferenceNode;
import br.edu.ifsp.syntacticTree.FactorNode;
import br.edu.ifsp.syntacticTree.IfNode;
import br.edu.ifsp.syntacticTree.InstanceofSentenceNode;
import br.edu.ifsp.syntacticTree.IntersectionNode;
import br.edu.ifsp.syntacticTree.JoinNode;
import br.edu.ifsp.syntacticTree.ListNode;
import br.edu.ifsp.syntacticTree.LogicalOperatorNode;
import br.edu.ifsp.syntacticTree.LogicalSentenceNode;
import br.edu.ifsp.syntacticTree.MultiplicationOperatorNode;
import br.edu.ifsp.syntacticTree.MultiplicationSentenceNode;
import br.edu.ifsp.syntacticTree.PrintTree;
import br.edu.ifsp.syntacticTree.ProjectNode;
import br.edu.ifsp.syntacticTree.QueryNode;
import br.edu.ifsp.syntacticTree.ReadyOnlyOperationsNode;
import br.edu.ifsp.syntacticTree.RelationNode;
import br.edu.ifsp.syntacticTree.RelationalOperationsNode;
import br.edu.ifsp.syntacticTree.RenameNode;
import br.edu.ifsp.syntacticTree.RenameSetNode;
import br.edu.ifsp.syntacticTree.SelectNode;
import br.edu.ifsp.syntacticTree.UnionNode;
import br.edu.ifsp.syntacticTree.UnitaryOperationsNode;
import br.edu.ifsp.syntacticTree.interfaces.BinaryOperationsNodeChildren;
import br.edu.ifsp.syntacticTree.interfaces.QueryNodeChildren;
import br.edu.ifsp.syntacticTree.interfaces.ReadyOnlyOperationsNodeChildren;
import br.edu.ifsp.syntacticTree.interfaces.RelationalOperationsNodeChildren;
import br.edu.ifsp.syntacticTree.interfaces.UnitaryOperationsNodeChildren;

public class RelationalQueryLanguage implements RelationalQueryLanguageConstants {

        /**
	 * Compiler version describe.
	 */
        public static final String VERSION = "Relational Query Language Translator 1.0 - 2010";

        /**
	 * Attribute used to check if there is or there is not abstract output of syntax analysis.
	 */
        private static boolean debug_sa = false; //debug lexical syntax analysis process

        /**
	 * Attribute used to store the syntactic tree from analysis
	 */
        private static ListNode root = null; //Store the syntactic tree

        /**
	 * Attribute used to check if the syntactic tree will be exported to a external file.
	 */
        private static boolean export_tree = false; //export a graph from syntactic tree

        /**
	 * Attribute used to store the symbol table from arguments
	 */
        private static SymbolTable symbolTable = null; //Stores the symbol table

        /**
	 * Method main of Relational Query Language class
	 * @throws ParseException, IOException
	 */
        public static void main ( String args[] ) throws ParseException, IOException {
                /**
		 * Attribute used to store a reference of a parser object that will do the compilation of source code in Relational Query Language.
		 */
                RelationalQueryLanguage parser = null;

                /**
		 * Attribute used to store the file name that will be analysis. 
		 */
                String fileName = null;

                /**
		 * Attribute used to store the output path.
		 */
                String outputPath = "./";

                /**
		 * Attribute used to store the output file name.
		 */
                String outputFileName = "Output.SQL";

                /**
		 * Number of parameters errors.
		 */
                int parametersErrors = 0;

                /**
		 * For clause used to get the parameters that will be used in compiler process.
		 */
                for ( int i = 0; i < args.length && parametersErrors == 0; i++ ) { //for 1

                        String arg = args[i];

                        if ( arg.toLowerCase().equals( "--debug-syntax-analysis" ) || arg.toLowerCase().equals( "-s" ) ) {

                                debug_sa = true;
                        }
                        /*
			 * Checking help parameter
			 */
                        else if ( arg.equals( "--help " ) || arg.equals( "-h" ) ) {

                                helpText();
                                System.exit( 0 );
                        }
                        /*
			 * Checking attributes parameter
			 */
                        else if (arg.equals("--attributes-definition") || arg.equals("-a")) {
                                i = checkParameterOfAttributesDefinition(args, i)-1;
                                if (i < 1) {
                                        helpText();
                                        System.exit(0);
                                }
                        }
                        /*
			 * Checking output-path parameter
			 */
                        else if ( arg.toLowerCase().equals( "--output-path" ) || arg.toLowerCase().equals( "-p" ) ) {

                                if ( i + 1 < args.length && checkParameterOfOutputPath( args[i+1] ) )
                                        outputPath = args[++i];
                                else {

                                        System.out.println( "The value of --output-path parameter is invalid." );
                                        parametersErrors++;
                                }
                        }
                        /*
			 * Checking output name parameter
			 */
                        else if ( arg.toLowerCase().equals( "--output-name" ) || arg.toLowerCase().equals( "-n" ) ) {

                                if ( i + 1 < args.length && checkParameterOfOutputName( args[i+1] ) )
                                        outputFileName = args[++i];

                                else {

                                        System.out.print( "The value of output-name parameter is invalid." );
                                        parametersErrors++;
                                }
                        }
                        /*
			 * Checking target SQL parameter.
			 */
                        else if ( arg.toLowerCase().equals( "--target-sql" ) || arg.toLowerCase().equals( "-t" ) ) {

                                if ( i + 1 < args.length && checkParameterOfTargetSQL( args[i+1] ) ) i++;

                                else {

                                        System.out.print( "The value of output-name parameter is invalid. It's just possible to use the SQL92 option." );
                                        parametersErrors++;
                                }
                        }
                        /*
			 * Checking export tree parameter
			 */
                        else if ( arg.equals("--export-tree") || arg.equals("-e")) {
                                export_tree = true;
                        }
                        /*
			 * Checking if the file is in the last index. 
			 */
                        else if ( i != args.length - 1 ) {

                                parametersErrors++;
                        }
                        /*
			 * All right. Now we go to do the compilation. 	
			 */
                        else
                                fileName = arg;
                } //for 1

                if ( parametersErrors != 0 ) {

                        System.out.println();
                        helpText();
                        System.exit(0);
                }
                else {

                        System.out.printf( "Reading from file %s\u005cn", fileName );

                        try {

                                parser = new RelationalQueryLanguage( new FileInputStream( fileName ) );

                                /*
				 * Disabling/Enabling the syntax analysis debug
				 */
                                if ( !debug_sa )
                                        parser.disable_tracing();
                                else
                                        parser.enable_tracing();
                        }
                        catch ( FileNotFoundException exception ) {

                                System.out.printf( "File %s not found.\u005cn", fileName );
                                System.exit(0);
                        }

                        /*
			 * Set a default output name if it is empty
			 */

                        try {

                                root = parser.program();
                                PrintTree pt = new PrintTree();
                                if (debug_sa)
                                        pt.printRoot(root);
                                if (export_tree)
                                        pt.exportDotTree(root);
                                RelationCheck rc = null;
                                int semanticErrors = 0;
                                if (symbolTable != null) {
                                        rc = new RelationCheck(symbolTable);
                                        semanticErrors = rc.semanticAnalysis(root);
                                        System.out.println("Semantic Errors: " + semanticErrors);
                                }
                                if (semanticErrors == 0) {
                                        CodeGenerator generator = new CodeGenerator(symbolTable, outputPath + outputFileName, VERSION);
                                        generator.generate(root);
                                }

                        }
                        catch ( NullPointerException exception ) {

                                System.out.println( "A file must be specified." );
                        }
                        finally {


                                switch ( parser.token_source.foundLexError() )  {
                                        case 0:
                                                System.out.println( "Lexical errors were not found." );
                                           break;

                                        case 1:
                                                System.out.printf( "%c[1m%i%c[0m lexical error was found.\u005cn", 27, 1, 27 );
                                          break;

                                        default:
                                                System.out.printf( "%c[1m%i%c[0m lexical errors were found.\u005cn", 27, parser.token_source.foundLexError(), 27 );
                                }

                                System.out.println( "Analysis finished." );
                        }
                }

        }//main

        /**
	 * Method used to link a founded token with his name.
	 * @see the book DELAMARO, M. E. Como Construir um Compilador: Utilizando Ferramentas Java. São Paulo: Novatec. 2004
	 * @param x
	 * @return
	 */
        public static String im ( int x ) {

                int k;
                String s;

                s = tokenImage[x];
                k = s.lastIndexOf( "\u005c"" );

                try {

                        s.substring( 1, k );
                }
                catch( Exception exception ) {}

                return s;
        }

        /**
	 * Method used to print the help text.
	 */
        private static void helpText() {

                System.out.println( "Usage: java -jar rql.jar [options] file" );
                System.out.println();

                System.out.println( "[options]" );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-p, --output-path <path-name>" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Specific output path" ) );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-n, --output-name <file-name>" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Specific output file name" ) );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-t, --target-sql <sql-type>",   "Target sql type (default: SQL92)" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Target sql type (default: SQL92)" ) );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-l, --debug-lexical-analysis" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Show lexical analysis details." ) );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-s, --debug-syntax-analysis" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Show syntax analysis details." ) );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-a, --attributes-definition" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Input the attributes definition for semantic analysis" ) );

                System.out.printf( "%c[1m", 27 );
                System.out.println( String.format( "\u005cn\u005ct\u00b7   %-30s", "-e, --export-tree" ) );
                System.out.printf( "%c[0m", 27 );
                System.out.println( String.format( "\u005cn\u005ct    %s", "Export the graph of syntactic tree." ) );

                System.out.println();
        }

        /**
	 * Method used to check the parameter value of --attributes-definition.
	 * @param location
	 *            is the start of parameters definition.
	 * @return the position of the next argument
	 */
        public static int checkParameterOfAttributesDefinition(String args[], int location) {
                boolean result = false;
                List<String> attributes = new ArrayList<String>();
                String attributeCheck = "";
                String identifierRegex = "([a-zA-Z_][a-zA-Z1-9_]*)";
                String typeRegex = "(VARCHAR|CHAR|INT|INTEGER|DOUBLE|DECIMAL|RATIONAL|FLOAT|LONG|BLOB)(\u005c\u005c([1-9]{1,3}\u005c\u005c))?";
                String primaryRegex = "(PRIMARY\u005c\u005cs?KEY)?";
                String foreignRegex = "(REFERENCES\u005c\u005cs?" + identifierRegex + "." + identifierRegex + ")?";
                String attributeRegex = identifierRegex + "." + identifierRegex + ":" + typeRegex + primaryRegex + foreignRegex
                                + ";";

                for (int i = location + 1; i < args.length - 1; i++) {
                        String parameter = args[i];
                        if (!parameter.equals("-p") && !parameter.equals("--output-path") && !parameter.equals("-n")
                                        && !parameter.equals("--output-name") && !parameter.equals("-t")
                                        && !parameter.equals("--target-sql") && !parameter.equals("-l")
                                        && !parameter.equals("--debug-lexical-analysis") && !parameter.equals("-s")
                                        && !parameter.equals("--debug-syntax-analysis") && !parameter.equals("-h")
                                        && !parameter.equals("--attributes-definition") && !parameter.equals("-a")
                                        && !parameter.equals("--export-tree") && !parameter.equals("-e")
                                        && !parameter.equals("--help")) {
                                attributes.add(parameter);
                                attributeCheck += parameter;
                                location = i;
                        } else {
                                location = i;
                                break;
                        }
                }
                if (!attributeCheck.matches("(" + attributeRegex + ")+")) {
                	System.out.println("Erro");
                        return 0;
                } else {
                	System.out.println("ENTROU");
                        System.out.println("Building symbol table from arguments:");
                        buildSymbolTable(attributeCheck, attributeRegex);
                }
                return location;
        }

        /**
	 * Method used to build the symbol table from arguments.
	 * @param definition
	 *            is the string with the information about the database
	 * @param regex
	 * 				is the regular expression that check the information
	 */
        public static void buildSymbolTable(String definition, String regex) {
                Pattern pattern = Pattern.compile(regex);
                Matcher matcher = pattern.matcher(definition);

                symbolTable = new SymbolTable();
                while (matcher.find()) {
                        String relation = matcher.group(1);
                        String attribute = matcher.group(2);
                        String type = matcher.group(3);

                        Attribute newAttribute = new Attribute(attribute, type);

                        int range = 0;
                        if (matcher.group(4) != null) {
                                range = Integer.parseInt(matcher.group(4).replace("(", "").replace(")", ""));
                                newAttribute.addFeature("range", range);
                        }

                        boolean primary = false;
                        if (matcher.group(5) != null) {
                                primary = true;
                                newAttribute.addFeature("primary", primary);
                        }

                        String referenceRelation = matcher.group(7);
                        String referenceAttribute = matcher.group(8);

                        if (referenceRelation != null) {
                                // Checks the foreign key
                                if (symbolTable.hasRelation(referenceRelation)
                                                && symbolTable.getRelation(referenceRelation).hasAttribute(referenceAttribute)) {
                                        newAttribute.addFeature("reference", new Reference(referenceRelation, referenceAttribute));
                                } else {
                                        // Throw a exception for unexistent foreign key
                                        throw new UnexistentForeignKeyException();
                                }
                        }

                        System.out.println("  Making a new entry:");
                        System.out.println("    Relation: " + relation);
                        System.out.println("    Attribute: " + attribute);
                        System.out.println("    Type: " + type);
                        System.out.println("    Range: " + range);
                        System.out.println("    Primary: " + primary);
                        System.out.println("    Reference relation: " + referenceRelation);
                        System.out.println("    Reference attribute: " + referenceAttribute);
                        System.out.println("  Closing entry:");

                        symbolTable.getRelation(relation).addAttribute(attribute, newAttribute);
                }
                System.out.println("Finished the construction of the symbol table");
        }

        /**
	 * Method used to check if the parameter value of --output-path, --output-name and target-sql are not equals compiler parameters .
	 * @param parameter is the value will be checked.
	 * @return true if the value that's OK
	 */
        public static boolean checkParameter ( String parameter ) {

                boolean result = false;

                if (
                        !parameter.equals( "-p" ) && !parameter.equals( "--output-path" )                    &&
                        !parameter.equals( "-n" ) && !parameter.equals( "--output-name" )                    &&
                        !parameter.equals( "-t" ) && !parameter.equals( "--target-sql" )                     &&
                        !parameter.equals( "-l" ) && !parameter.equals( "--debug-lexical-analysis" )         &&
                        !parameter.equals( "-s" ) && !parameter.equals( "--debug-syntax-analysis"  )         &&
                        !parameter.equals( "-h" ) && !parameter.equals( "--help" )

                ) {

                        result = true;
                }

                return result;
        }

        /**
	 * Method used to check the parameter value of --output-name.
	 * @param parameter is the value will be checked.
	 * @return true if the value that's OK
	 */
        public static boolean checkParameterOfOutputName (String parameter ) {

                boolean result = false;

                if ( parameter != null && checkParameter( parameter ) )
                        result = true;

                return result;
        }

        /**
	 * Method used to check the parameter value of --output-path.
	 * @param parameter is the value will be checked.
	 * @return true if the value that's OK
	 */
        public static boolean checkParameterOfOutputPath ( String parameter ) {

                boolean result = false;

                if ( parameter.indexOf( "-" ) != 0 && parameter != null && checkParameter( parameter ) )
                        result = true;

                return result;
        }

        /**
	 * Method used to check the parameter value of --target-sql.
	 * @param parameter is the value will be checked.
	 * @return true if the value that's OK
	 */
        public static boolean checkParameterOfTargetSQL ( String parameter ) {

                boolean result = false;

                if ( parameter.toUpperCase().equals( "SQL92" ) )
                        result = true;

                return result;
        }

/* **************************************************************************************************************
/*                                                Syntax Definition 											*
/* **************************************************************************************************************/
  final public ListNode program() throws ParseException {
    trace_call("program");
    try {
   RelationalOperationsNode r = null;
   ListNode l = null;
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LEFT_PARENTHESIS:
        case PROJECT_TOKEN:
        case SELECT_TOKEN:
        case RENAME_TOKEN:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        r = relationalOperations();
        jj_consume_token(SEMICOLON);
              if ( l == null ) l = new ListNode( r );
              else l.add( r );
      }
      jj_consume_token(0);
          {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("program");
    }
  }

  final public RelationalOperationsNode relationalOperations() throws ParseException {
    trace_call("relationalOperations");
    try {
   RelationalOperationsNodeChildren opnd = null;
      opnd = query();
     {if (true) return new RelationalOperationsNode( (QueryNode) opnd );}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("relationalOperations");
    }
  }

  final public QueryNode query() throws ParseException {
    trace_call("query");
    try {
   QueryNodeChildren qnc = null;
      qnc = readyOnlyOperations();
          {if (true) return new QueryNode( qnc );}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("query");
    }
  }

  final public ReadyOnlyOperationsNode readyOnlyOperations() throws ParseException {
    trace_call("readyOnlyOperations");
    try {
        ReadyOnlyOperationsNodeChildren roonc = null;
      if (jj_2_1(2)) {
        roonc = binaryOperations();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROJECT_TOKEN:
        case SELECT_TOKEN:
        case RENAME_TOKEN:
        case IDENTIFIER:
          roonc = unitaryOperations();
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
          {if (true) return new ReadyOnlyOperationsNode(roonc);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("readyOnlyOperations");
    }
  }

  final public BinaryOperationsNode binaryOperations() throws ParseException {
    trace_call("binaryOperations");
    try {
        BinaryOperationsNodeChildren bonc = null;
        BinarySetNode bst = null;
        ReadyOnlyOperationsNode roon1 = null;
        ReadyOnlyOperationsNode roon2 = null;
        RelationNode rn1 = null;
        RelationNode rn2 = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_PARENTHESIS:
        jj_consume_token(LEFT_PARENTHESIS);
        roon1 = readyOnlyOperations();
        jj_consume_token(RIGHT_PARENTHESIS);
        break;
      case IDENTIFIER:
        rn1 = relation();
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        bonc = union();
        break;
      case AND:
        bonc = intersection();
        break;
      case MINUS_SIGN:
        bonc = difference();
        break;
      case LEFT_BRACKET:
      case NATURAL_JOIN_TOKEN:
        bonc = join();
        break;
      case CROSS_TOKEN:
        bonc = crossjoin();
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_PARENTHESIS:
        jj_consume_token(LEFT_PARENTHESIS);
        roon2 = readyOnlyOperations();
        jj_consume_token(RIGHT_PARENTHESIS);
        break;
      case IDENTIFIER:
        rn2 = relation();
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        bst = new BinarySetNode();
        if(roon1 != null) bst.addFirstRelation(roon1); else bst.addFirstRelation(rn1);
        if(roon2 != null) bst.addSecondRelation(roon2); else bst.addSecondRelation(rn2);
        {if (true) return new BinaryOperationsNode(bonc, bst);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("binaryOperations");
    }
  }

  final public UnionNode union() throws ParseException {
    trace_call("union");
    try {
        Token t = null;
      t = jj_consume_token(OR);
          {if (true) return new UnionNode(t);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("union");
    }
  }

  final public IntersectionNode intersection() throws ParseException {
    trace_call("intersection");
    try {
        Token t = null;
      t = jj_consume_token(AND);
          {if (true) return new IntersectionNode(t);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("intersection");
    }
  }

  final public DifferenceNode difference() throws ParseException {
    trace_call("difference");
    try {
        Token t = null;
      t = jj_consume_token(MINUS_SIGN);
          {if (true) return new DifferenceNode(t);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("difference");
    }
  }

  final public CrossJoinNode crossjoin() throws ParseException {
    trace_call("crossjoin");
    try {
        Token t = null;
      t = jj_consume_token(CROSS_TOKEN);
          {if (true) return new CrossJoinNode(t);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("crossjoin");
    }
  }

  final public JoinNode join() throws ParseException {
    trace_call("join");
    try {
        LogicalSentenceNode lsn = null;
        Token t = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NATURAL_JOIN_TOKEN:
        t = jj_consume_token(NATURAL_JOIN_TOKEN);
        break;
      case LEFT_BRACKET:
        t = jj_consume_token(LEFT_BRACKET);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LEFT_PARENTHESIS:
        case NOT:
        case INTEGER:
        case DECIMAL:
        case HEX:
        case OCT:
        case BIN:
        case STRING:
        case TRUE:
        case FALSE:
        case IDENTIFIER:
          lsn = logicalSentence();
          break;
        default:
          jj_la1[5] = jj_gen;
          ;
        }
        jj_consume_token(RIGHT_BRACKET);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          if(lsn == null) {if (true) return new JoinNode(t);} else {if (true) return new JoinNode(t, lsn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("join");
    }
  }

//DivisionNode division() : {
//	Token t = null;
//} {
//	t = < SOLIDUS >
//	{ return new DivisionNode(t); }
//}
  final public UnitaryOperationsNode unitaryOperations() throws ParseException {
    trace_call("unitaryOperations");
    try {
        UnitaryOperationsNodeChildren uonc = null;
        ReadyOnlyOperationsNode roon = null;
        RelationNode rn = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROJECT_TOKEN:
      case SELECT_TOKEN:
      case RENAME_TOKEN:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROJECT_TOKEN:
          uonc = project();
          break;
        case SELECT_TOKEN:
          uonc = select();
          break;
        case RENAME_TOKEN:
          uonc = rename();
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(LEFT_PARENTHESIS);
        roon = readyOnlyOperations();
        jj_consume_token(RIGHT_PARENTHESIS);
                                                                                   {if (true) return new UnitaryOperationsNode(uonc, roon);}
        break;
      case IDENTIFIER:
        rn = relation();
                             {if (true) return new UnitaryOperationsNode( rn );}
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("unitaryOperations");
    }
  }

  final public ProjectNode project() throws ParseException {
    trace_call("project");
    try {
        ListNode ln = null;
        Token token = null;
      jj_consume_token(PROJECT_TOKEN);
      token = jj_consume_token(IDENTIFIER);
          ln = new ListNode( new AttributeNode( token ) );
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMMA);
        token = jj_consume_token(IDENTIFIER);
           ln.add( new AttributeNode( token ) );
      }
          {if (true) return new ProjectNode(ln);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("project");
    }
  }

  final public SelectNode select() throws ParseException {
    trace_call("select");
    try {
        LogicalSentenceNode lsn = null;
      jj_consume_token(SELECT_TOKEN);
      lsn = logicalSentence();
     {if (true) return new SelectNode(lsn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("select");
    }
  }

  final public RenameNode rename() throws ParseException {
    trace_call("rename");
    try {
        ListNode ln = null;
        Token t1 = null, t2 = null;
      jj_consume_token(RENAME_TOKEN);
      t1 = jj_consume_token(IDENTIFIER);
      t2 = jj_consume_token(IDENTIFIER);
     if(ln==null) ln = new ListNode( new RenameSetNode(t1, t2) );
        else ln.add( new RenameSetNode(t1, t2) );
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[10] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        t1 = jj_consume_token(IDENTIFIER);
        t2 = jj_consume_token(IDENTIFIER);
          if(ln==null) ln = new ListNode( new RenameSetNode(t1, t2) );
        else ln.add( new RenameSetNode(t1, t2) );
      }
     {if (true) return new RenameNode(ln);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("rename");
    }
  }

  final public RelationNode relation() throws ParseException {
    trace_call("relation");
    try {
        Token t = null;
      t = jj_consume_token(IDENTIFIER);
     {if (true) return new RelationNode(t);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("relation");
    }
  }

  final public LogicalSentenceNode logicalSentence() throws ParseException {
    trace_call("logicalSentence");
    try {
        ConditionalSentenceNode csn1 = null;
        ConditionalSentenceNode csn2 = null;
        LogicalOperatorNode lon = null;
        LogicalOperatorNode temp = null;
        Token t = null;
      csn1 = conditionalSentence();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
        case OR:
        case XOR:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_4;
        }
        t = logicalOperator();
        csn2 = conditionalSentence();
                if(lon == null) { lon = new LogicalOperatorNode(t, csn1, csn2);
                temp = lon;
                }else{
                        temp.add(t, csn2);
                        temp = temp.getNextLogicalOperatorNode();
                }
      }
                if(lon==null) {if (true) return new LogicalSentenceNode(csn1);}
                else {if (true) return new LogicalSentenceNode(lon);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("logicalSentence");
    }
  }

  final public ConditionalSentenceNode conditionalSentence() throws ParseException {
    trace_call("conditionalSentence");
    try {
        ComparisonSentenceNode csn = null;
        ComparisonSentenceNode csn1 = null;
        ComparisonSentenceNode csn2 = null;
        ListNode ln = null;
        Token t = null;
      csn = comparisonSentence();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_5;
        }
        t = jj_consume_token(IF);
        csn1 = comparisonSentence();
        jj_consume_token(COLON);
        csn2 = comparisonSentence();
                if(ln == null) ln = new ListNode(new IfNode(t, csn1, csn2)); else ln.add(new IfNode(t, csn1, csn2));
      }
          if(ln==null) {if (true) return new ConditionalSentenceNode(csn);} else {if (true) return new ConditionalSentenceNode(csn, ln);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("conditionalSentence");
    }
  }

  final public ComparisonSentenceNode comparisonSentence() throws ParseException {
    trace_call("comparisonSentence");
    try {
        InstanceofSentenceNode isn1 = null;
        InstanceofSentenceNode isn2 = null;
        ComparisonOperatorNode con = null;
        ComparisonOperatorNode temp = null;
        Token t = null;
      isn1 = instanceofSentence();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LESS_THAN:
        case EQUALS:
        case NOT_EQUALS:
        case GREATER_THAN:
        case GREATER_THAN_OR_EQUALS:
        case LESS_THAN_OR_EQUALS:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_6;
        }
        t = comparisonOperator();
        isn2 = instanceofSentence();
                if(con == null){
                        con = new ComparisonOperatorNode(t, isn1, isn2);
                        temp = con;
           }else{
                        temp.add(t, isn2);
                        temp = temp.getNextComparisonOperatorNode();
           }
      }
                if(con==null) {if (true) return new ComparisonSentenceNode(isn1);}
                else {if (true) return new ComparisonSentenceNode(con);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("comparisonSentence");
    }
  }

  final public InstanceofSentenceNode instanceofSentence() throws ParseException {
    trace_call("instanceofSentence");
    try {
        AdditionSentenceNode asn = null;
        Token type = null;
      asn = additionSentence();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INSTANCEOF:
        jj_consume_token(INSTANCEOF);
        type = type();
        break;
      default:
        jj_la1[14] = jj_gen;
        ;
      }
     if(type != null) {if (true) return new InstanceofSentenceNode(asn);}
   else {if (true) return new InstanceofSentenceNode(asn, type);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("instanceofSentence");
    }
  }

  final public AdditionSentenceNode additionSentence() throws ParseException {
    trace_call("additionSentence");
    try {
        MultiplicationSentenceNode msn1 = null;
        MultiplicationSentenceNode msn2 = null;
        AdditionOperatorNode aon = null;
        AdditionOperatorNode temp = null;
        Token t = null;
      msn1 = multiplicationSentence();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS_SIGN:
        case MINUS_SIGN:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_7;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS_SIGN:
          t = jj_consume_token(PLUS_SIGN);
          break;
        case MINUS_SIGN:
          t = jj_consume_token(MINUS_SIGN);
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        msn2 = multiplicationSentence();
                if(aon == null){
                        aon = new AdditionOperatorNode(t, msn1, msn2);
                        temp = aon;
           }else{
                        temp.add(t, msn2);
                        temp = temp.getNextAdditionOperatorNode();
           }
      }
                if(aon==null) {if (true) return new AdditionSentenceNode(msn1);}
                else {if (true) return new AdditionSentenceNode(aon);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("additionSentence");
    }
  }

  final public MultiplicationSentenceNode multiplicationSentence() throws ParseException {
    trace_call("multiplicationSentence");
    try {
        FactorNode fn1 = null;
        FactorNode fn2 = null;
        MultiplicationOperatorNode mon = null;
        MultiplicationOperatorNode temp = null;
        Token t = null;
      fn1 = factor();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PERCENT:
        case ASTERISK:
        case SOLIDUS:
        case POWER:
          ;
          break;
        default:
          jj_la1[17] = jj_gen;
          break label_8;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ASTERISK:
          t = jj_consume_token(ASTERISK);
          break;
        case POWER:
          t = jj_consume_token(POWER);
          break;
        case SOLIDUS:
          t = jj_consume_token(SOLIDUS);
          break;
        case PERCENT:
          t = jj_consume_token(PERCENT);
          break;
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        fn2 = factor();
           if(mon == null){
                        mon = new MultiplicationOperatorNode(t, fn1, fn2);
                        temp = mon;
           }else{
                        temp.add(t, fn2);
                        temp = temp.getNextMultiplicationOperatorNode();
           }
      }
                if(mon==null) {if (true) return new MultiplicationSentenceNode(fn1);}
                else {if (true) return new MultiplicationSentenceNode(mon);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("multiplicationSentence");
    }
  }

  final public FactorNode factor() throws ParseException {
    trace_call("factor");
    try {
        Token not = null;
        Token t = null;
        ConditionalSentenceNode csn = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
        not = jj_consume_token(NOT);
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case DECIMAL:
      case HEX:
      case OCT:
      case BIN:
      case STRING:
      case TRUE:
      case FALSE:
        t = literal();
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        break;
      case LEFT_PARENTHESIS:
        jj_consume_token(LEFT_PARENTHESIS);
        csn = conditionalSentence();
        jj_consume_token(RIGHT_PARENTHESIS);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
     if(csn == null) {if (true) return new FactorNode(not, t);} else {if (true) return new FactorNode(not, csn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("factor");
    }
  }

  final public Token logicalOperator() throws ParseException {
    trace_call("logicalOperator");
    try {
        Token t = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        t = jj_consume_token(AND);
        break;
      case OR:
        t = jj_consume_token(OR);
        break;
      case XOR:
        t = jj_consume_token(XOR);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
     {if (true) return t;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("logicalOperator");
    }
  }

  final public Token comparisonOperator() throws ParseException {
    trace_call("comparisonOperator");
    try {
        Token t = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS_THAN:
        t = jj_consume_token(LESS_THAN);
        break;
      case LESS_THAN_OR_EQUALS:
        t = jj_consume_token(LESS_THAN_OR_EQUALS);
        break;
      case GREATER_THAN:
        t = jj_consume_token(GREATER_THAN);
        break;
      case GREATER_THAN_OR_EQUALS:
        t = jj_consume_token(GREATER_THAN_OR_EQUALS);
        break;
      case EQUALS:
        t = jj_consume_token(EQUALS);
        break;
      case NOT_EQUALS:
        t = jj_consume_token(NOT_EQUALS);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
     {if (true) return t;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("comparisonOperator");
    }
  }

  final public Token literal() throws ParseException {
    trace_call("literal");
    try {
        Token t = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
        t = jj_consume_token(INTEGER);
        break;
      case DECIMAL:
        t = jj_consume_token(DECIMAL);
        break;
      case HEX:
        t = jj_consume_token(HEX);
        break;
      case OCT:
        t = jj_consume_token(OCT);
        break;
      case BIN:
        t = jj_consume_token(BIN);
        break;
      case STRING:
        t = jj_consume_token(STRING);
        break;
      case TRUE:
        t = jj_consume_token(TRUE);
        break;
      case FALSE:
        t = jj_consume_token(FALSE);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          {if (true) return t;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("literal");
    }
  }

  final public Token type() throws ParseException {
    trace_call("type");
    try {
        Token t = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VARCHAR_TYPE:
        t = jj_consume_token(VARCHAR_TYPE);
        break;
      case CHAR_TYPE:
        t = jj_consume_token(CHAR_TYPE);
        break;
      case INTEGER_TYPE:
        t = jj_consume_token(INTEGER_TYPE);
        break;
      case DOUBLE_TYPE:
        t = jj_consume_token(DOUBLE_TYPE);
        break;
      case FLOAT_TYPE:
        t = jj_consume_token(FLOAT_TYPE);
        break;
      case BLOB_TYPE:
        t = jj_consume_token(BLOB_TYPE);
        break;
      case GEOMETRIC_TYPE:
        t = jj_consume_token(GEOMETRIC_TYPE);
        break;
      case RELATION_TYPE:
        t = jj_consume_token(RELATION_TYPE);
        break;
      case BOOLEAN_TYPE:
        t = jj_consume_token(BOOLEAN_TYPE);
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          {if (true) return t;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("type");
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_33() {
    if (!jj_rescan) trace_call("select(LOOKING AHEAD...)");
    if (jj_scan_token(SELECT_TOKEN)) { if (!jj_rescan) trace_return("select(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("select(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_23() {
    if (!jj_rescan) trace_call("crossjoin(LOOKING AHEAD...)");
    if (jj_scan_token(CROSS_TOKEN)) { if (!jj_rescan) trace_return("crossjoin(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("crossjoin(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_24() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (!jj_rescan) trace_call("project(LOOKING AHEAD...)");
    if (jj_scan_token(PROJECT_TOKEN)) { if (!jj_rescan) trace_return("project(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("project(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (!jj_rescan) trace_call("difference(LOOKING AHEAD...)");
    if (jj_scan_token(MINUS_SIGN)) { if (!jj_rescan) trace_return("difference(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("difference(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_17() {
    if (!jj_rescan) trace_call("readyOnlyOperations(LOOKING AHEAD...)");
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) { if (!jj_rescan) trace_return("readyOnlyOperations(LOOKAHEAD FAILED)"); return true; }
    }
    { if (!jj_rescan) trace_return("readyOnlyOperations(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_11() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (!jj_rescan) trace_call("intersection(LOOKING AHEAD...)");
    if (jj_scan_token(AND)) { if (!jj_rescan) trace_return("intersection(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("intersection(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_31() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_26() {
    if (!jj_rescan) trace_call("unitaryOperations(LOOKING AHEAD...)");
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) { if (!jj_rescan) trace_return("unitaryOperations(LOOKAHEAD FAILED)"); return true; }
    }
    { if (!jj_rescan) trace_return("unitaryOperations(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_19() {
    if (!jj_rescan) trace_call("union(LOOKING AHEAD...)");
    if (jj_scan_token(OR)) { if (!jj_rescan) trace_return("union(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("union(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_18() {
    if (!jj_rescan) trace_call("relation(LOOKING AHEAD...)");
    if (jj_scan_token(IDENTIFIER)) { if (!jj_rescan) trace_return("relation(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("relation(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_16() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(LEFT_BRACKET)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (!jj_rescan) trace_call("rename(LOOKING AHEAD...)");
    if (jj_scan_token(RENAME_TOKEN)) { if (!jj_rescan) trace_return("rename(LOOKAHEAD FAILED)"); return true; }
    { if (!jj_rescan) trace_return("rename(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_13() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (!jj_rescan) trace_call("join(LOOKING AHEAD...)");
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_3R_25()) { if (!jj_rescan) trace_return("join(LOOKAHEAD FAILED)"); return true; }
    }
    { if (!jj_rescan) trace_return("join(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  private boolean jj_3R_12() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(LEFT_PARENTHESIS)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_9() {
    if (!jj_rescan) trace_call("binaryOperations(LOOKING AHEAD...)");
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_10()) {
    jj_scanpos = xsp;
    if (jj_3R_11()) { if (!jj_rescan) trace_return("binaryOperations(LOOKAHEAD FAILED)"); return true; }
    }
    xsp = jj_scanpos;
    if (jj_3R_12()) {
    jj_scanpos = xsp;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) {
    jj_scanpos = xsp;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) { if (!jj_rescan) trace_return("binaryOperations(LOOKAHEAD FAILED)"); return true; }
    }
    }
    }
    }
    { if (!jj_rescan) trace_return("binaryOperations(LOOKAHEAD SUCCEEDED)"); return false; }
  }

  /** Generated Token Manager. */
  public RelationalQueryLanguageTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[25];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x200,0x0,0x200,0x10004000,0x200,0x200,0x10000000,0x0,0x0,0x2000,0x2000,0x0,0x0,0x1f80000,0x0,0x5000,0x5000,0x10880,0x10880,0x0,0x200,0x0,0x1f80000,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x38,0x38,0x0,0xc180,0x0,0xf8020000,0x100,0x38,0x38,0x0,0x0,0x1c000,0x2,0x0,0x1,0x0,0x0,0x4,0x4,0x20000,0xf8000000,0x1c000,0x0,0xf8000000,0x7fc0000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x8,0x8,0x8,0x0,0x8,0xf,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xf,0x0,0x0,0x7,0x8,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public RelationalQueryLanguage(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RelationalQueryLanguage(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RelationalQueryLanguageTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public RelationalQueryLanguage(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RelationalQueryLanguageTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public RelationalQueryLanguage(RelationalQueryLanguageTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(RelationalQueryLanguageTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    } else {
      trace_scan(jj_scanpos, kind);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[81];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 25; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 81; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private int trace_indent = 0;
  private boolean trace_enabled = true;

/** Enable tracing. */
  final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
    trace_enabled = false;
  }

  private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
